require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MoneyApps' do
  config = use_native_modules!
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  use_react_native!(:path => config["reactNativePath"])


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'MoneyAppsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MoneyApps-tvOS' do
  # Pods for MoneyApps-tvOS

  target 'MoneyApps-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
